name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Welcome optit Lab"
      - name: Print goodbye
        run: echo "My First Workflow executed successfully"
